surdstream/urls.py
from translations import views

from rest_framework import routers
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static


router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)


urlpatterns = [
    re_path(r'^', include(router.urls)),
    re_path(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

#    path('accounts/', include('django.contrib.auth.urls')),
#    path('accounts/profile/', views.profile, name='profile'),

    path('accounts/signup/', views.signup, name='signup'),
    re_path(r'^accounts/activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.activate, name='activate'),
#    path('accounts/activate/<str:uidb64>/<str:token>/', views.activate, name='activate'),

    path('accounts/login/', views.login, name='login'),
    path('accounts/logout/', views.logout, name='logout'),

    path('', views.index, name='index'),
    path('translations/', include('translations.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

translations/urls.py
from django.urls import path, include

from . import views


app_name = 'translations'
urlpatterns = [
    # ex: /translations/
    path('', views.index, name='index'),
    # ex: /translations/results?search_query=hello
    path('results/', views.search_results, name='search_results'),
    # ex: /translations/new/
    path('new/', views.add_translation, name='add_translation'),
    # ex: /translations/5/
    path('<int:word_id>/', views.detail, name='detail'),
    # ex: /translations/9/vote/
    path('<int:video_id>/vote/', views.vote, name='vote'),

    #remove_this
    path('remove_this/', views.remove_this, name='remove_this'),
    path('upload_video/', views.upload_video, name='upload_video'),
]

translations/models.py
from .video_uploader import upload_video_to_youtube

from django.db import models
from django.contrib.auth.models import AbstractUser

from typing import Tuple, List


class User(AbstractUser):
    email_confirmed = models.BooleanField(default=False)
    # def video_vote_value(self, video_id: int):
    pass
#    rated_videos = models.ManyToManyField('TranslationVideo', related_name='voted_users', through='UserVote')


class Word(models.Model):
    word_text = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.word_text

# class WordTranslationVideo(models.Model):
#     word = models.ForeignKey(Word, on_delete=models.CASCADE)
#     translation_video = models.ForeignKey(TranslationVideo, on_delete=models.CASCADE)


class TranslationVideo(models.Model):
    author = models.ForeignKey(User, models.SET_NULL, blank=True, null=True)
#    words = models.ManyToManyField(Word, related_name='videos')
    words = models.ManyToManyField(Word, related_name='videos', through='VideoWord')
#    video_url = models.CharField(max_length=500)  # models.URLField
#    video_file = models.FileField(upload_to='videos/%Y/%m/', max_length=150)
    youtube_id = models.CharField(max_length=50, unique=True, blank=True, null=True)
    votes = models.IntegerField(default=0)
    voted_users = models.ManyToManyField(User, related_name='rated_videos', through='UserVote')
    upload_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        words_str = '[' + ', '.join(map(str, self.words.all())) + ']'
        return 'Video ' + self.youtube_id + ' ' + words_str

    @staticmethod
    def new_videos():
        return TranslationVideo.objects.order_by('upload_date')[:5]

    def user_vote_value(self, user_id: int) -> int:
        user_vote_records = UserVote.objects.filter(user_id=user_id, video=self)
        assert len(user_vote_records) <= 1, \
            'There can be only one record of UserVote for the specific user and the video'
        return user_vote_records[0].vote if user_vote_records else 0

    @staticmethod
    def upload_video(file, words: List[str]) -> Tuple[int, str]:
        return upload_video_to_youtube(file, words)


class VideoWord(models.Model):
    video = models.ForeignKey(TranslationVideo, on_delete=models.CASCADE)
    word = models.ForeignKey(Word, on_delete=models.CASCADE)
    match = models.FloatField()  # coincidence percent


class DeletedTranslationVideo(models.Model):
    author_name = models.CharField(max_length=100, blank=True, null=True)
    words = models.CharField(max_length=200)
    video_file = models.FileField(max_length=150) #(upload_to='deleted_videos/%Y/%m/', max_length=150)
    votes = models.IntegerField()
    upload_date = models.DateTimeField()
    deleting_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'DeletedVideo ' + self.video_file.url + ' ' + self.words


class UserVote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    video = models.ForeignKey(TranslationVideo, on_delete=models.CASCADE)
    vote = models.IntegerField()
    last_modified_date = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ("user", "video")

    @staticmethod
    def rollback_user_votes(user: User):
        user_vote_records = UserVote.objects.filter(user=user)
        for user_vote_record in user_vote_records:
            user_vote_record.video.votes -= user_vote_record.vote
            user_vote_record.video.save()

translations/forms.py
from .models import User

from django import forms
from django.contrib.auth.forms import UserCreationForm


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)

translations/views.py
from .models import Word, TranslationVideo, UserVote, User, VideoWord
from .forms import SignUpForm
from .tokens import account_activation_token
from .serializers import UserSerializer, GroupSerializer

from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse, HttpResponse, Http404
from django.views.decorators.csrf import ensure_csrf_cookie
from django.contrib.auth import (
    login as auth_login,
    logout as auth_logout,
    authenticate as auth
)
from django.core.mail import send_mail
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.models import Group
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.conf import settings
from rest_framework import viewsets


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer


@ensure_csrf_cookie
def remove_this(request):

    word_list = Word.objects.all()

    login_form = AuthenticationForm(auto_id='login_id_%s')
    login_form.fields['username'].widget.attrs['placeholder'] = "Username"
    login_form.fields['password'].widget.attrs['placeholder'] = "Password"

    signup_form = SignUpForm(auto_id='signup_id_%s')
    signup_form.fields['username'].widget.attrs['placeholder'] = "Username"
    signup_form.fields['email'].widget.attrs['placeholder'] = "Email"
    signup_form.fields['password1'].widget.attrs['placeholder'] = "Password"
    signup_form.fields['password2'].widget.attrs['placeholder'] = "Confirm"

    context = {'words': word_list, 'new_videos': TranslationVideo.new_videos(),
               'login_form': login_form, 'signup_form': signup_form}

    return render(request, 'translations/new-base.html', context)


@ensure_csrf_cookie
def index(request):
    word_list = Word.objects.all()

    login_form = AuthenticationForm(auto_id='login_id_%s')
    signup_form = SignUpForm(auto_id='signup_id_%s')

    context = {'words': word_list, 'new_videos': TranslationVideo.new_videos(),
               'login_form': login_form, 'signup_form': signup_form}
    return render(request, 'translations/index.html', context)


def search_results(request):
    if request.method == 'GET':
        search_start = request.GET['search_query']
        result_videos = TranslationVideo.objects.filter(
            words__word_text__istartswith=search_start).order_by('-votes')[:8]
        videos_json_list = [{'id': v.id,
                             'youtube_id': v.youtube_id,
                             'author': v.author.username,
                             'votes': v.votes} for v in result_videos]
        return JsonResponse({'videos': videos_json_list})
    raise Http404("Only accepts AJAX, method GET")


def signup(request):
    if request.method == 'POST':
        signup_form = SignUpForm(request.POST)
        if signup_form.is_valid():
            user = signup_form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            subject = 'Activate Your SurdStream Account'
            context = {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token': account_activation_token.make_token(user),
            }
            txt_message = render_to_string('registration/activation-email.txt', context)
            html_message = render_to_string('registration/activation-email.html', context)
            send_mail(subject, txt_message, from_email=settings.DEFAULT_FROM_EMAIL,
                      recipient_list=[user.email], html_message=html_message)
        return JsonResponse({'user_id': request.user.id,
                             'field_errors': signup_form.errors.as_json()})
    raise Http404("Only accepts AJAX, method POST")

    #         signup_form.save()
    #         username = signup_form.cleaned_data.get('username')
    #         raw_password = signup_form.cleaned_data.get('password1')
    #         user = auth(username=username, password=raw_password)
    #         auth_login(request, user)
    #     return JsonResponse({'user_id': request.user.id,
    #                          'field_errors': signup_form.errors.as_json()})
    # raise Http404("Only accepts AJAX, method POST")


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.email_confirmed = True
        user.save()
        # auth_login(request, user)
        return render(request, 'registration/email-confirmed.html', {'username': user.username})
    return Http404("Invalid email confirmation link")


def login(request):
    if request.method == 'POST':
        login_form = AuthenticationForm(request, request.POST)
        if login_form.is_valid():
            auth_login(request, login_form.get_user())
        response_data = {'user_id': request.user.id,
                         'field_errors': login_form.errors.as_json()}
        return JsonResponse(response_data)
    raise Http404("Only accepts AJAX, method POST")


def logout(request):
    if request.method == 'POST':
        auth_logout(request)
        return JsonResponse({'user_id': request.user.id})


def upload_video(request):
    if request.method == 'POST':
        print("UPLOAD VIDEO, post: ", request.POST)
        print("files: ", request.FILES)
        words = [w.strip() for w in request.POST['tags'].split(',') if w.strip()]
        file = request.FILES['file']
        if file.size < 5242880 and words:  # 5 MB
            print("before upload")
            status_code, video_id = TranslationVideo.upload_video(file, words)

            video_record = TranslationVideo.objects.create(author=request.user, youtube_id=video_id)
            match = 1
            for word_text in words:
                word, created = Word.objects.get_or_create(word_text=word_text)
                VideoWord.objects.create(video=video_record, word=word, match=match)
                if match > 0.6:
                    match -= 0.1
            return JsonResponse({'status_code': status_code,
                                 'video_id': video_id})
        return JsonResponse({'error': 'incorrect data'})
    raise Http404("Only accepts AJAX, method POST")


@ensure_csrf_cookie
def detail(request, word_id):
    word = get_object_or_404(Word, pk=word_id)
    word_videos = word.videos.all()
    user_votes = [video.user_vote_value(request.user.id) for video in word_videos]
    return render(request, 'translations/detail.html',
                  {'word': word, 'videos_and_votes': list(zip(word_videos, user_votes))})


def vote(request, video_id):
    new_delta_vote = int(request.POST['vote'])
    user_vote, created = UserVote.objects.update_or_create(
        user=request.user, video_id=video_id,
        defaults={'vote': new_delta_vote},
    )
    data = {'new_total_votes': user_vote.video.votes,
            'user_vote': new_delta_vote}
    return JsonResponse(data)


@login_required
def profile(request):
    return render(request, 'accounts/profile.html', {})


@login_required
def add_translation(request):
    if request.method == 'POST':
        words = [w.strip() for w in request.POST['words'].split(',') if w.strip()]
        file = request.FILES['file']
        if file.size < 5242880 and words:  # 5 MB
            video_record = TranslationVideo(author=request.user, video_file=file)
            video_record.save()
            for word_text in words:
                word, created = Word.objects.get_or_create(word_text=word_text)
                video_record.words.add(word)
            return redirect(profile)
        else:
            return HttpResponse(status=413)
    return render(request, 'translations/new.html', {})

translations/templates/translations/detail.html
{% extends "base.html" %}
{% block content %}

{% load static %}

{{ word }}
{% for video, user_vote in videos_and_votes %}
    <br>
    <video width="300" height="300" controls autoplay>
        <source src="{{ video.video_file.url }}" type="video/webm">
    </video>
    <br>
    Votes: <span id="total-votes">{{ video.votes }}</span>
    <br>
    {% if user.is_authenticated %}
        User vote: <span id="user-vote">{{ user_vote }}</span>

        <button name="vote" value="1"
                id="vote-up" class="js-process-vote"
                vote-url="{% url 'translations:vote' video.id %}"
                {% if user_vote == 1 %} disabled {% endif %}>Vote up</button>
        <button name="vote" value="-1"
                id="vote-down" class="js-process-vote"
                vote-url="{% url 'translations:vote' video.id %}"
                {% if user_vote == -1 %} disabled {% endif %}>Vote down</button>
    {% else %}
        User not logged in
        <button name="vote" value="1" title="Login, please" disabled>Vote up</button>
        <button name="vote" value="-1" title="Login, please" disabled>Vote down</button>
    {% endif %}

    <br>
    {% for word_video in video.words.all %}
        {{ word_video }};
    {% endfor %}
    <br>
{% endfor %}

<script src="https://code.jquery.com/jquery-3.3.0.min.js"
        integrity="sha256-RTQy8VOmNlT6b2PIRur37p6JEBZUE7o8wPgMvu18MC4="
        crossorigin="anonymous"></script>
<script src="{% static 'translations/js/ajax-handlers.js' %}"></script>

{% endblock %}

translations/templates/translations/footer.html
<footer class="footer text-center">
    Back to top
</footer>

translations/templates/translations/header.html
<nav class="navbar fixed-top navbar-light bg-light">
  <a class="navbar-brand mr-auto" href="#">Surdstream</a>

  <button id="addVideoBtn" type="button" class="btn btn-success mr-2" data-toggle="tooltip" data-placement="left" title="Add"><i class="fas fa-plus fa-1x"></i></button>

  <!-- Button trigger modal -->

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="#main-page">Главная<span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="#wordlist">Все слова</a>
      <a class="nav-item nav-link" href="#questions">Вопросы</a>
      <a class="nav-item nav-link" href="#profile">Профиль</a>

      <div id="menu-logout" class="row mx-0">
        <a id="logout-link" class="nav-item nav-link" href="{% url 'logout' %}" {% if not user.is_authenticated %} hidden {% endif %}>Выйти</a>
        {% comment %}
        <a class="nav-image ml-2" href="#" title="Добавить слово" data-toggle="modal" data-target="#exampleModalCenter">
          <img class="rounded-circle" src="holder.js/50x50"/>
        </a>

        <a class="nav-image ml-2" href="#">
          <img class="rounded-circle" src="holder.js/50x50"/>
          <span class="oi oi-menu" title="menu" aria-hidden="true"></span>
        </a>
        {% endcomment %}
      </div>

      <div id="menu-login" class="row mx-0" {% if user.is_authenticated %} hidden {% endif %}>
        <div class="col-6 pr-1 pl-0">
          <button id="logInButton" type="button" style="width:100%;" class="btn btn-success" data-toggle="modal" data-target="#logInModal">
            Вход
          </button>
        </div>
        <div class="col-6 pl-1 pr-0">
          <button id="signInButton" type="button" style="width:100%;" class="btn btn-secondary" data-toggle="modal" data-target="#signInModal">
            Регистрация
          </button>
        </div>
      </div>
    </div>
  </div>
</nav>

translations/templates/translations/index.html
{% extends 'translations/base.html' %}

  {% block content %}

    <div class="container">
      <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">        <h4>Последние видео</h4></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false"><h4>Набирающие популярность</h4></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false"><h4>Лучшие видео</h4></a>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">

        <ul>
          <li>
            <div class='row publication'>
              <p class="col-6 text-left"><span>+</span><span>Рука&nbsp;</span>нога,тело,мерка</p>
              <p class="col-6 text-right">Author</p>
              <div class="col-12 video_placeholder">
                <div class="row">
                  <div class="col-6 text-center">
                    <iframe src="https://www.youtube.com/embed/tgbNymZ7vqY"></iframe>
                    <p><a href='#'>+</a>&nbsp;<span>9999</span>&nbsp;<a href='#'>-</a></p>
                  </div>
                  <div class="col-6">
                    <div style="height:70%; background-color:blue">
                      <p>Comment1</p>
                      <p>Comment2</p>
                    </div>
                    <div style="height:30%; background-color:green">
                      <input type='text'/>
                      <button>Send</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </li>
        </ul>

      </div>
      <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">2</div>
      <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">3</div>
    </div>
  </div>
</div>



  {% endblock %}

translations/templates/translations/log-in.html
{% load widget_tweaks %}

<!-- LOG IN -->
<div class="modal fade" id="logInModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Авторизация</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form id="login-form" method="post" action="{% url 'login' %}">
          <p id="login-error" hidden>Your username and password didn't match. Please try again.</p>
          <div class="form-group">
            <label for="username">Email address</label>
            {{ login_form.username| add_class:"form-control"| attr:"placeholder:Email" }}
          </div>
          <div class="form-group">
            <label for="password">Password</label>
            {{ login_form.password|add_class:"form-control"| attr:"placeholder:Password" }}
          </div>
          <div class="form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">Запомнить меня</label>
          </div>
          <a class="small" href="#">Восстановление пароля</a>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Отменить</button>
            <button type="submit" class="btn btn-primary">Отправить</button>
          </div>
        </form>
        {% comment %}
        <form>
          <input type="text" placeholder="Email" />
          <input type="password" placeholder="password" />
          <button>Submit</button>
        </form>
        {% endcomment %}
      </div>
    </div>
  </div>
</div>

translations/templates/translations/main-page.html
<div id="main-page">

  <!-- SEARCH -->
  <div id="search" class="container">
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
      <div class="container">
        <div class="row">
          <a class="col-2 col-sm-4 arrow" href="#carouselExampleControls" role="button" data-slide="prev">
            {% comment %}
              <i data-fa-transform="down-0" class="fas fa-angle-left fa-2x"></i>
            {% endcomment %}
            <i data-fa-transform="down-2" class="fas fa-angle-left fa-2x"></i>
            <span class="px-2">Previous</span>
          </a>
          <p class="col-8 col-sm-4 text-center">
            Лучшее
          </p>
          <a class="col-2 col-sm-4 arrow text-right" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="px-2">Next</span>
            {% comment %}
              <i data-fa-transform="down-0" class="fas fa-angle-right fa-2x"></i>
            {% endcomment %}
            <i data-fa-transform="down-2" class="fas fa-angle-right fa-2x"></i>
          </a>
        </div>
      </div>

      <div class="carousel-inner">
        <div class="carousel-item active">
          {% comment %}
            <img class="d-block w-100" src="holder.js/1920x300?text=First slide&random=yes">
          {% endcomment %}

          <div class="container">
            <div class="row">
              {% include "translations/video-link.html" %}
              {% include "translations/video-link.html" %}
            </div>
          </div>

        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src="holder.js/1920x300?text=Second slide&random=yes">
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src="holder.js/1920x300?text=Third slide&random=yes">
        </div>
      </div>
    </div>
  </div>
</div>

translations/templates/translations/new-base.html
{% load staticfiles %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!--OWN STYLES-->
    <link rel="stylesheet" href="{% static 'translations/css/new-style.css' %}" />
    <link rel="stylesheet" href="{% static 'translations/css/main.min.css' %}" />

    <!-- Scripts -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    <script src="{% static 'translations/js/holder/holder.js' %}"></script>

    <title>Surdstream</title>

  </style>
</head>

<body>

  {% include 'translations/header.html' %}

    <main class="container">

    {% comment %}
      AUTH
    {% endcomment %}
    {% include "translations/sign-up.html" %}
    {% include "translations/log-in.html" %}

    {% comment %}
      CONTENT
    {% endcomment %}
    {% include "translations/profile.html" %}
    {% include "translations/questions.html" %}
    {% include "translations/wordlist.html" %}

    {% include "translations/main-page.html" %}
    {% include "translations/video-full.html" %}

    </main>

    <section class="container d-none" id="addVideo">
      {% include "translations/add-video.html" %}
    </section>

    {% comment %}
      SLIDER
      {% include "translations/slider.html" %}
    {% endcomment %}


    {% include "translations/footer.html" %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
			  src="https://code.jquery.com/jquery-3.3.1.min.js"
			  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
			  crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{% static 'translations/js/new-index.js' %}"></script>
    <script src="{% static 'translations/js/ajax-handlers.js' %}"></script>
    <script src="{% static 'translations/js/upload-video.js' %}"></script>
  </body>
</html>

translations/templates/translations/new.html
{% extends "base.html" %}
{% block content %}

{% load static %}

<h1>New translation</h1>

<form method="POST" enctype="multipart/form-data">{% csrf_token %}
    Words: <input name="words" type="text" size="50">
    <br>
    <br>
    <input id="file-input" name="file" type="file" accept=".webm, .avi, .mp4">
    <br>
    <br>
    Max file size: 5 MB
    <br>
    Supported formats: *.webm, *.ogg, *.avi, *.mp4
    <br>
    <br>
    <button id="upload" type="submit" class="save btn btn-default" disabled>Upload</button>
</form>


<script src="https://code.jquery.com/jquery-3.3.0.min.js"
        integrity="sha256-RTQy8VOmNlT6b2PIRur37p6JEBZUE7o8wPgMvu18MC4="
        crossorigin="anonymous"></script>
<script src="{% static 'translations/js/new.js' %}"></script>

{% endblock %}

translations/templates/translations/questions.html
<div id="questions" style="display:none" >
  <div id="search" class="container">
    <div class="input-group input-group-lg">
      <div class="input-group-prepend">
        <span class="input-group-text" id="inputGroup-sizing-lg">Поиск</span>
      </div>
      <input type="text" class="form-control" aria-label="Large" aria-describedby="inputGroup-sizing-sm" placeholder="Введите вопрос">
    </div>
  </div>
  <button type="button" class="btn btn-info btn-block">Задать вопрос</button>
</div>